# HPA for Backend - Critical for handling API load spikes
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: ecommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  # CPU-based scaling - Essential for API processing loads
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale when average CPU > 70%
  # Memory-based scaling - Important for data-heavy operations
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale when average memory > 80%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60    # Wait 1 min before scaling up again
      policies:
      - type: Percent
        value: 50     # Scale up by 50% of current replicas
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300   # Wait 5 min before scaling down
      policies:
      - type: Percent
        value: 10     # Scale down by 10% to avoid thrashing
        periodSeconds: 60
---
# HPA for Frontend - Optimized for user traffic patterns
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: ecommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 3
  maxReplicas: 15   # Higher max for user-facing service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # More aggressive scaling for better UX
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30    # Faster scaling for user-facing service
      policies:
      - type: Percent
        value: 100    # Double replicas quickly during traffic spikes
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 600   # Slower scale-down to handle traffic patterns
      policies:
      - type: Percent
        value: 5      # Very conservative scale-down
        periodSeconds: 60
