apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
  namespace: ecommerce
spec:
  template:
    spec:
      containers:
      - name: load-test
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting load test..."
          for i in $(seq 1 1000); do
            wget -q -O- http://frontend-service:80/ &
            wget -q -O- http://frontend-service:80/api/products &
            if [ $((i % 10)) -eq 0 ]; then
              echo "Completed $i requests"
              sleep 1
            fi
          done
          wait
          echo "Load test completed!"
      restartPolicy: Never
  backoffLimit: 4