apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api-deployment
  labels:
    app: hello-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      # Node Affinity config
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: environment
                operator: In
                values:
                - production
      # Allows scheduling on nodes with specific taints
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "api-workload"
        effect: "NoSchedule"
      containers:
      - name: hello-api
        image: ghcr.io/riyaknol11/hello-api-task:latest
        imagePullPolicy: Always  # Keeping Always for Pull from registry
        ports:
        - containerPort: 8080
        # For Resource requests and limits
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        # For Health checks
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-api-service
spec:
  selector:
    app: hello-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer